project_id = "tjukbsdfuuqnvbcxetph"

[functions.seed-game-data]
verify_jwt = false

[functions.ai-match-simulator]
verify_jwt = false

[functions.ai-match-commentary]
verify_jwt = false

[functions.populate-real-players]
verify_jwt = true

